name: Release

on:
  workflow_dispatch:
    inputs:
      publishNuget:
        type: boolean
        default: true
      publishApi:
        type: boolean
        default: true
      publishReact:
        type: boolean
        default: true

jobs:
  nuget:
    name: Publish NuGet Package
    if: ${{ inputs.publishNuget }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: MorganMWJ.WordsearchMaker

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - run: dotnet restore
      - run: dotnet build -c Release
      - run: dotnet test -c Release

      - name: Pack
        run: |
          dotnet pack -c Release \
          -o artifacts

      - name: Push
        run: |
          dotnet nuget push artifacts/*.nupkg \
          --api-key ${{ secrets.NUGET_API_KEY }} \
          --source https://api.nuget.org/v3/index.json \
          --skip-duplicate
  api:
    name: Publish API (Azure Function)
    if: ${{ inputs.publishApi }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Publish Function App
        run: |
          dotnet publish MorganMWJ.WordsearchMaker/MorganMWJ.WordsearchMaker.Api \
          -c Release \
          -o ./publish

      - name: 'Deploy to Azure Functions'
        uses: Azure/functions-action@v1
        with:
          app-name: wordsearch-generator-api
          package: './publish'

  react:
    name: Publish React App
    if: ${{ inputs.publishReact }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: wordsearch-react-app/package-lock.json

      - name: Install dependencies
        working-directory: wordsearch-react-app
        run: npm ci

      - name: Build
        working-directory: wordsearch-react-app
        run: npm run build

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: wordsearch-react-app/dist

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
